package com.llanquihuetour.ui;

import com.llanquihuetour.data.GestorPersonas;
import com.llanquihuetour.model.Cliente;
import com.llanquihuetour.model.Direccion;
import com.llanquihuetour.util.CargadorCombobox;
import com.llanquihuetour.util.RutInvalidoException;
import com.llanquihuetour.util.ValidadorGeneral;
import com.llanquihuetour.util.ValidadorRut;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;

/**
 * Clase que representa la interfaz gráfica para registrar un Cliente.
 * @author Jaime Seguel.
 * @since Semana 9
 */
public class VentanaCliente extends JDialog {

    // Declaración de los elementos de la ventana.
    private JTextField txtNombre;
    private JTextField txtRut;
    private JLabel lblRut;
    private JLabel lblNombre;
    private JTextField txtTelefono;
    private JComboBox cmbRegion;
    private JComboBox cmbCiudad;
    private JTextField txtCalle;
    private JTextField txtNumeroCasa;
    private JTextField txtEdad;
    private JTextField txtIdioma;
    private JTextField txtContacto;
    private JButton btnRegistrarCliente;
    private JButton btnCancelarRegistro;
    private JPanel btnTelefono;
    private JLabel lblTelefono;
    private JLabel lblRegion;
    private JLabel lblCiudad;
    private JLabel lblCalle;
    private JLabel lblNumeroCasa;
    private JLabel lblEdad;
    private JLabel lblIdioma;
    private JLabel lblContacto;
    private JPanel ventanaCliente;
    private JPanel contenedorBtns;

    /**
     * Constructor de la Ventana Cliente.
     * @param parent Ventana padre desde donde se invoca.
     */
    public VentanaCliente(JDialog parent) {

        super(parent, "Registrar Cliente", true);
        this.setContentPane(ventanaCliente);
        this.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
        this.pack();
        this.setLocationRelativeTo(parent);

        // Evento del botón Cancelar.
        btnCancelarRegistro.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {

                dispose();
            }
        });

        // Evento del botón Registrar.
        btnRegistrarCliente.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {

                registrarCliente();
            }
        });

        // Llama al método que carga los combobox de region y ciudad al iniciar la ventana.
        CargadorCombobox.cargarRegiones(cmbRegion);
        CargadorCombobox.actualizarCiudades(cmbRegion.getSelectedItem().toString(), cmbCiudad);

        // Actualización dinámica de ciudades al cambiar región
        cmbRegion.addItemListener(new ItemListener() {

            @Override
            public void itemStateChanged(ItemEvent e) {

                if (e.getStateChange() == ItemEvent.SELECTED) {
                    CargadorCombobox.actualizarCiudades(e.getItem().toString(), cmbCiudad);
                }
            }
        });
    }

    /**
     * Método que extrae, valida y guarda los datos del cliente en un .txt.
     */
    private void registrarCliente() {

        String nombre = txtNombre.getText();
        String rut = txtRut.getText();
        String telefono = txtTelefono.getText();
        String region = cmbRegion.getSelectedItem().toString();
        String ciudad = cmbCiudad.getSelectedItem().toString();
        String calle = txtCalle.getText();
        String numero = txtNumeroCasa.getText();
        String idioma = txtIdioma.getText();
        String contacto = txtContacto.getText();
        String edadStr = txtEdad.getText();

        if (ValidadorGeneral.validarCamposVacios(nombre, rut, telefono, calle, numero, idioma, contacto, edadStr)) {
            return;
        }

        if (!ValidadorGeneral.validarTelefono(telefono)) {
            return;
        }

        int edad = ValidadorGeneral.validarEntero(edadStr, "Edad");
        if (edad == -1) {
            return;
        }

        if (ValidadorRut.validarRutGUI(rut) == null) {
            return;
        }

        Direccion direccion = new Direccion(calle, numero, ciudad, region);
        Cliente cliente = new Cliente(idioma, edad, contacto, nombre, rut, telefono, direccion);

        GestorPersonas gestor = new GestorPersonas();
        gestor.agregarPersona(cliente);

        JOptionPane.showMessageDialog(this, "Cliente registrado exitosamente.", "Registro Exitoso", JOptionPane.INFORMATION_MESSAGE);
        dispose();
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        ventanaCliente = new JPanel();
        ventanaCliente.setLayout(new GridBagLayout());
        lblNombre = new JLabel();
        lblNombre.setText("Nombre: ");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.EAST;
        gbc.insets = new Insets(10, 10, 10, 10);
        ventanaCliente.add(lblNombre, gbc);
        lblRut = new JLabel();
        lblRut.setText("R.U.T: ");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.EAST;
        gbc.insets = new Insets(10, 10, 10, 10);
        ventanaCliente.add(lblRut, gbc);
        txtNombre = new JTextField();
        txtNombre.setMaximumSize(new Dimension(350, 30));
        txtNombre.setMinimumSize(new Dimension(350, 30));
        txtNombre.setPreferredSize(new Dimension(350, 30));
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(10, 10, 10, 10);
        ventanaCliente.add(txtNombre, gbc);
        txtRut = new JTextField();
        txtRut.setMaximumSize(new Dimension(350, 30));
        txtRut.setMinimumSize(new Dimension(350, 30));
        txtRut.setPreferredSize(new Dimension(350, 30));
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(10, 10, 10, 10);
        ventanaCliente.add(txtRut, gbc);
        lblTelefono = new JLabel();
        lblTelefono.setText("Teléfono: ");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.anchor = GridBagConstraints.EAST;
        gbc.insets = new Insets(10, 10, 10, 10);
        ventanaCliente.add(lblTelefono, gbc);
        lblRegion = new JLabel();
        lblRegion.setText("Región: ");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.anchor = GridBagConstraints.EAST;
        gbc.insets = new Insets(10, 10, 10, 10);
        ventanaCliente.add(lblRegion, gbc);
        lblCiudad = new JLabel();
        lblCiudad.setText("Ciudad: ");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 4;
        gbc.anchor = GridBagConstraints.EAST;
        gbc.insets = new Insets(10, 10, 10, 10);
        ventanaCliente.add(lblCiudad, gbc);
        lblCalle = new JLabel();
        lblCalle.setText("Calle: ");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 5;
        gbc.anchor = GridBagConstraints.EAST;
        gbc.insets = new Insets(10, 10, 10, 10);
        ventanaCliente.add(lblCalle, gbc);
        lblNumeroCasa = new JLabel();
        lblNumeroCasa.setText("Número de casa: ");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 6;
        gbc.anchor = GridBagConstraints.EAST;
        gbc.insets = new Insets(10, 10, 10, 10);
        ventanaCliente.add(lblNumeroCasa, gbc);
        lblEdad = new JLabel();
        lblEdad.setText("Edad: ");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 7;
        gbc.anchor = GridBagConstraints.EAST;
        gbc.insets = new Insets(10, 10, 10, 10);
        ventanaCliente.add(lblEdad, gbc);
        lblIdioma = new JLabel();
        lblIdioma.setText("Idioma: ");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 8;
        gbc.anchor = GridBagConstraints.EAST;
        gbc.insets = new Insets(10, 10, 10, 10);
        ventanaCliente.add(lblIdioma, gbc);
        lblContacto = new JLabel();
        lblContacto.setText("Contacto de emergencia: ");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 9;
        gbc.anchor = GridBagConstraints.EAST;
        gbc.insets = new Insets(10, 10, 10, 10);
        ventanaCliente.add(lblContacto, gbc);
        txtTelefono = new JTextField();
        txtTelefono.setMaximumSize(new Dimension(350, 30));
        txtTelefono.setMinimumSize(new Dimension(350, 30));
        txtTelefono.setPreferredSize(new Dimension(350, 30));
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 2;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(10, 10, 10, 10);
        ventanaCliente.add(txtTelefono, gbc);
        cmbRegion = new JComboBox();
        cmbRegion.setMaximumSize(new Dimension(350, 30));
        cmbRegion.setMinimumSize(new Dimension(350, 30));
        cmbRegion.setPreferredSize(new Dimension(350, 30));
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 3;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(10, 10, 10, 10);
        ventanaCliente.add(cmbRegion, gbc);
        cmbCiudad = new JComboBox();
        cmbCiudad.setMaximumSize(new Dimension(350, 30));
        cmbCiudad.setMinimumSize(new Dimension(350, 30));
        cmbCiudad.setPreferredSize(new Dimension(350, 30));
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 4;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(10, 10, 10, 10);
        ventanaCliente.add(cmbCiudad, gbc);
        txtCalle = new JTextField();
        txtCalle.setMaximumSize(new Dimension(350, 30));
        txtCalle.setMinimumSize(new Dimension(350, 30));
        txtCalle.setPreferredSize(new Dimension(350, 30));
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 5;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(10, 10, 10, 10);
        ventanaCliente.add(txtCalle, gbc);
        txtNumeroCasa = new JTextField();
        txtNumeroCasa.setMaximumSize(new Dimension(350, 30));
        txtNumeroCasa.setMinimumSize(new Dimension(350, 30));
        txtNumeroCasa.setPreferredSize(new Dimension(350, 30));
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 6;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(10, 10, 10, 10);
        ventanaCliente.add(txtNumeroCasa, gbc);
        txtEdad = new JTextField();
        txtEdad.setMaximumSize(new Dimension(350, 30));
        txtEdad.setMinimumSize(new Dimension(350, 30));
        txtEdad.setPreferredSize(new Dimension(350, 30));
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 7;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(10, 10, 10, 10);
        ventanaCliente.add(txtEdad, gbc);
        txtIdioma = new JTextField();
        txtIdioma.setMaximumSize(new Dimension(350, 30));
        txtIdioma.setMinimumSize(new Dimension(350, 30));
        txtIdioma.setPreferredSize(new Dimension(350, 30));
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 8;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(10, 10, 10, 10);
        ventanaCliente.add(txtIdioma, gbc);
        txtContacto = new JTextField();
        txtContacto.setMaximumSize(new Dimension(350, 30));
        txtContacto.setMinimumSize(new Dimension(350, 30));
        txtContacto.setPreferredSize(new Dimension(350, 30));
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 9;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(10, 10, 10, 10);
        ventanaCliente.add(txtContacto, gbc);
        contenedorBtns = new JPanel();
        contenedorBtns.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 10;
        gbc.gridwidth = 2;
        gbc.fill = GridBagConstraints.BOTH;
        ventanaCliente.add(contenedorBtns, gbc);
        btnRegistrarCliente = new JButton();
        btnRegistrarCliente.setText("Registrar Cliente");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(10, 10, 10, 10);
        contenedorBtns.add(btnRegistrarCliente, gbc);
        btnCancelarRegistro = new JButton();
        btnCancelarRegistro.setText("Cancelar Registro");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(10, 10, 10, 10);
        contenedorBtns.add(btnCancelarRegistro, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return ventanaCliente;
    }

}
