package com.llanquihuetour.ui;

import com.llanquihuetour.data.GestorCatalogo;
import com.llanquihuetour.model.PaseoLacustre;
import com.llanquihuetour.util.CargadorCombobox;
import com.llanquihuetour.util.ValidadorGeneral;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;

/**
 * Clase que representa la interfaz gráfica para registrar un Paseo Lacustre.
 * @author Jaime Seguel.
 * @since Semana 9
 */
public class VentanaPaseoLacustre extends JDialog {

    // Declaración de los elementos de la ventana.
    private JPanel ventanaPaseo;
    private JButton btnRegistrarPaseo;
    private JTextField txtCodigo;
    private JTextField txtNombre;
    private JTextField txtDuracion;
    private JTextField txtComuna;
    private JTextField txtPrecio;
    private JComboBox cmbPermitePescar;
    private JTextField txtCapacidadPasajeros;
    private JTextField txtTipoEmbarcacion;
    private JTextField txtHorario;
    private JButton btnCancelarRegistro;
    private JLabel lblCodigo;
    private JLabel lblNombre;
    private JLabel lblDuracion;
    private JLabel lblComuna;
    private JLabel lblPrecio;
    private JLabel lblHorario;
    private JLabel lblEmbarcacion;
    private JLabel lblCapacidad;
    private JLabel lblPermitePescar;
    private JPanel contenedorBtns;

    /**
     * Constructor de la Ventana Paseo Lacustre.
     * @param parent Ventana padre desde donde se invoca.
     */
    public VentanaPaseoLacustre(JDialog parent) {

        super(parent, "Registrar Paseo Lacustre", true);
        this.setContentPane(ventanaPaseo);
        this.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
        this.pack();
        this.setLocationRelativeTo(parent);

        // Evento del botón Cancelar.
        btnCancelarRegistro.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                dispose();
            }
        });

        // Evento del botón Registrar.
        btnRegistrarPaseo.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                registrarPaseo();
            }
        });

        // Llama al método que carga el combobox del booleano al iniciar la ventana.
        CargadorCombobox.cargarOpcionesSiNo(cmbPermitePescar);
    }

    /**
     * Método que extrae, valida y guarda los datos del paseo lacustre en un .txt.
     */
    private void registrarPaseo() {

        String codigoStr = txtCodigo.getText();
        String nombre = txtNombre.getText();
        String duracionStr = txtDuracion.getText();
        String precioStr = txtPrecio.getText();
        String comuna = txtComuna.getText();
        String horario = txtHorario.getText();
        String embarcacion = txtTipoEmbarcacion.getText();
        String capacidadStr = txtCapacidadPasajeros.getText();
        boolean pesca = cmbPermitePescar.getSelectedItem().toString().equals("Sí");

        if (ValidadorGeneral.validarCamposVacios(codigoStr, nombre, duracionStr, precioStr, horario, embarcacion, capacidadStr)) {

            return;
        }

        int codigo = ValidadorGeneral.validarEntero(codigoStr, "Código");

        if (codigo == -1) {

            return;
        }

        double duracion = ValidadorGeneral.validarDecimal(duracionStr, "Duración");

        if (duracion == -1.0) {

            return;
        }

        double precio = ValidadorGeneral.validarDecimal(precioStr, "Precio");

        if (precio == -1.0) {

            return;
        }

        int capacidad = ValidadorGeneral.validarEntero(capacidadStr, "Capacidad");

        if (capacidad == -1) {

            return;
        }

        PaseoLacustre paseo = new PaseoLacustre(codigo, nombre, duracion, comuna, precio, horario, embarcacion, pesca, capacidad);

        GestorCatalogo gestor = new GestorCatalogo();
        gestor.agregarProducto(paseo);

        JOptionPane.showMessageDialog(this, "Paseo Lacustre registrado exitosamente.", "Registro Exitoso", JOptionPane.INFORMATION_MESSAGE);
        dispose();
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        ventanaPaseo = new JPanel();
        ventanaPaseo.setLayout(new GridBagLayout());
        lblCodigo = new JLabel();
        lblCodigo.setText("Código: ");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.EAST;
        gbc.insets = new Insets(10, 10, 10, 10);
        ventanaPaseo.add(lblCodigo, gbc);
        lblNombre = new JLabel();
        lblNombre.setText("Nombre: ");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.EAST;
        gbc.insets = new Insets(10, 10, 10, 10);
        ventanaPaseo.add(lblNombre, gbc);
        lblDuracion = new JLabel();
        lblDuracion.setText("Duración (Horas): ");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.anchor = GridBagConstraints.EAST;
        gbc.insets = new Insets(10, 10, 10, 10);
        ventanaPaseo.add(lblDuracion, gbc);
        lblComuna = new JLabel();
        lblComuna.setText("Comuna: ");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.anchor = GridBagConstraints.EAST;
        gbc.insets = new Insets(10, 10, 10, 10);
        ventanaPaseo.add(lblComuna, gbc);
        lblPrecio = new JLabel();
        lblPrecio.setText("Precio ($): ");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 4;
        gbc.anchor = GridBagConstraints.EAST;
        gbc.insets = new Insets(10, 10, 10, 10);
        ventanaPaseo.add(lblPrecio, gbc);
        lblHorario = new JLabel();
        lblHorario.setText("Horario: ");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 5;
        gbc.anchor = GridBagConstraints.EAST;
        gbc.insets = new Insets(10, 10, 10, 10);
        ventanaPaseo.add(lblHorario, gbc);
        lblEmbarcacion = new JLabel();
        lblEmbarcacion.setText("Tipo de Embarcación: ");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 6;
        gbc.anchor = GridBagConstraints.EAST;
        gbc.insets = new Insets(10, 10, 10, 10);
        ventanaPaseo.add(lblEmbarcacion, gbc);
        lblCapacidad = new JLabel();
        lblCapacidad.setText("Capacidad de Pasajeros: ");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 7;
        gbc.anchor = GridBagConstraints.EAST;
        gbc.insets = new Insets(10, 10, 10, 10);
        ventanaPaseo.add(lblCapacidad, gbc);
        lblPermitePescar = new JLabel();
        lblPermitePescar.setText("¿Permite Pescar?: ");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 8;
        gbc.anchor = GridBagConstraints.EAST;
        gbc.insets = new Insets(10, 10, 10, 10);
        ventanaPaseo.add(lblPermitePescar, gbc);
        txtCodigo = new JTextField();
        txtCodigo.setMaximumSize(new Dimension(350, 30));
        txtCodigo.setMinimumSize(new Dimension(350, 30));
        txtCodigo.setPreferredSize(new Dimension(350, 30));
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(10, 10, 10, 10);
        ventanaPaseo.add(txtCodigo, gbc);
        txtNombre = new JTextField();
        txtNombre.setMaximumSize(new Dimension(350, 30));
        txtNombre.setMinimumSize(new Dimension(350, 30));
        txtNombre.setPreferredSize(new Dimension(350, 30));
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(10, 10, 10, 10);
        ventanaPaseo.add(txtNombre, gbc);
        txtDuracion = new JTextField();
        txtDuracion.setMaximumSize(new Dimension(350, 30));
        txtDuracion.setMinimumSize(new Dimension(350, 30));
        txtDuracion.setPreferredSize(new Dimension(350, 30));
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 2;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(10, 10, 10, 10);
        ventanaPaseo.add(txtDuracion, gbc);
        txtComuna = new JTextField();
        txtComuna.setMaximumSize(new Dimension(350, 30));
        txtComuna.setMinimumSize(new Dimension(350, 30));
        txtComuna.setPreferredSize(new Dimension(350, 30));
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 3;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(10, 10, 10, 10);
        ventanaPaseo.add(txtComuna, gbc);
        txtPrecio = new JTextField();
        txtPrecio.setMaximumSize(new Dimension(350, 30));
        txtPrecio.setMinimumSize(new Dimension(350, 30));
        txtPrecio.setPreferredSize(new Dimension(350, 30));
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 4;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(10, 10, 10, 10);
        ventanaPaseo.add(txtPrecio, gbc);
        cmbPermitePescar = new JComboBox();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 8;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(10, 10, 10, 10);
        ventanaPaseo.add(cmbPermitePescar, gbc);
        txtCapacidadPasajeros = new JTextField();
        txtCapacidadPasajeros.setMaximumSize(new Dimension(350, 30));
        txtCapacidadPasajeros.setMinimumSize(new Dimension(350, 30));
        txtCapacidadPasajeros.setPreferredSize(new Dimension(350, 30));
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 7;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(10, 10, 10, 10);
        ventanaPaseo.add(txtCapacidadPasajeros, gbc);
        txtTipoEmbarcacion = new JTextField();
        txtTipoEmbarcacion.setMaximumSize(new Dimension(350, 30));
        txtTipoEmbarcacion.setMinimumSize(new Dimension(350, 30));
        txtTipoEmbarcacion.setPreferredSize(new Dimension(350, 30));
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 6;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(10, 10, 10, 10);
        ventanaPaseo.add(txtTipoEmbarcacion, gbc);
        txtHorario = new JTextField();
        txtHorario.setMaximumSize(new Dimension(350, 30));
        txtHorario.setMinimumSize(new Dimension(350, 30));
        txtHorario.setPreferredSize(new Dimension(350, 30));
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 5;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(10, 10, 10, 10);
        ventanaPaseo.add(txtHorario, gbc);
        contenedorBtns = new JPanel();
        contenedorBtns.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 9;
        gbc.gridwidth = 2;
        gbc.fill = GridBagConstraints.BOTH;
        ventanaPaseo.add(contenedorBtns, gbc);
        btnRegistrarPaseo = new JButton();
        btnRegistrarPaseo.setText("Registrar Paseo Lacustre");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(10, 10, 10, 10);
        contenedorBtns.add(btnRegistrarPaseo, gbc);
        btnCancelarRegistro = new JButton();
        btnCancelarRegistro.setText("Cancelar Registro");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(10, 10, 10, 10);
        contenedorBtns.add(btnCancelarRegistro, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return ventanaPaseo;
    }

}
