package com.llanquihuetour.ui;

import com.llanquihuetour.data.GestorPersonas;
import com.llanquihuetour.model.Empleado;
import com.llanquihuetour.model.Direccion;
import com.llanquihuetour.util.CargadorCombobox;
import com.llanquihuetour.util.RutInvalidoException;
import com.llanquihuetour.util.ValidadorGeneral;
import com.llanquihuetour.util.ValidadorRut;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;

/**
 * Clase que representa la interfaz gráfica para registrar un Empleado.
 * @author Jaime Seguel.
 * @since Semana 9
 */
public class VentanaEmpleado extends JDialog {

    // Declaración de los elementos de la ventana.
    private JTextField txtNombre;
    private JTextField txtRut;
    private JTextField txtTelefono;
    private JComboBox cmbRegion;
    private JComboBox cmbCiudad;
    private JTextField txtCalle;
    private JTextField txtNumero;
    private JTextField txtCargo;
    private JTextField txtTurno;
    private JTextField txtSueldo;
    private JButton btnRegistrarEmpleado;
    private JButton btnCancelarRegistro;
    private JLabel lblNombre;
    private JLabel lblRut;
    private JLabel lblTelefono;
    private JLabel lblRegion;
    private JLabel lblCiudad;
    private JLabel lblCalle;
    private JLabel lblNumeroCasa;
    private JLabel lblCargo;
    private JLabel lblTurno;
    private JLabel lblSueldo;
    private JPanel ventanaEmpleado;
    private JPanel contenedorBtns;

    /**
     * Constructor de la Ventana Empleado.
     * @param parent Ventana padre desde donde se invoca.
     */
    public VentanaEmpleado(JDialog parent) {

        super(parent, "Registrar Empleado", true);
        this.setContentPane(ventanaEmpleado);
        this.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
        this.pack();
        this.setLocationRelativeTo(parent);

        // Evento del botón Cancelar.
        btnCancelarRegistro.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                dispose();
            }
        });

        // Evento del botón Registrar
        btnRegistrarEmpleado.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                registrarEmpleado();
            }
        });

        // Llama al método que carga los combobox de region y ciudad al iniciar la ventana.
        CargadorCombobox.cargarRegiones(cmbRegion);
        CargadorCombobox.actualizarCiudades(cmbRegion.getSelectedItem().toString(), cmbCiudad);

        // Actualización dinámica de ciudades al cambiar región
        cmbRegion.addItemListener(new ItemListener() {

            @Override
            public void itemStateChanged(ItemEvent e) {

                if (e.getStateChange() == ItemEvent.SELECTED) {
                    CargadorCombobox.actualizarCiudades(e.getItem().toString(), cmbCiudad);
                }
            }
        });
    }

    /**
     * Método que extrae, valida y guarda los datos del empleado.
     */
    private void registrarEmpleado() {

        String nombre = txtNombre.getText();
        String rut = txtRut.getText();
        String telefono = txtTelefono.getText();
        String region = cmbRegion.getSelectedItem().toString();
        String ciudad = cmbCiudad.getSelectedItem().toString();
        String calle = txtCalle.getText();
        String numero = txtNumero.getText();
        String cargo = txtCargo.getText();
        String turno = txtTurno.getText();
        String sueldoStr = txtSueldo.getText();

        if (ValidadorGeneral.validarCamposVacios(nombre, rut, telefono, calle, numero, cargo, turno, sueldoStr)) {
            return;
        }

        if (!ValidadorGeneral.validarTelefono(telefono)) {
            return;
        }

        double sueldo = ValidadorGeneral.validarDecimal(sueldoStr, "Sueldo");
        if (sueldo == -1.0) {
            return;
        }

        if (ValidadorRut.validarRutGUI(rut) == null) {
            return;
        }

        Direccion direccion = new Direccion(calle, numero, ciudad, region);
        Empleado empleado = new Empleado(cargo, turno, sueldo, nombre, rut, telefono, direccion);

        GestorPersonas gestor = new GestorPersonas();
        gestor.agregarPersona(empleado);

        JOptionPane.showMessageDialog(this, "Empleado registrado exitosamente.", "Registro Exitoso", JOptionPane.INFORMATION_MESSAGE);
        dispose();
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        ventanaEmpleado = new JPanel();
        ventanaEmpleado.setLayout(new GridBagLayout());
        lblNombre = new JLabel();
        lblNombre.setText("Nombre: ");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.EAST;
        gbc.insets = new Insets(10, 10, 10, 10);
        ventanaEmpleado.add(lblNombre, gbc);
        lblRut = new JLabel();
        lblRut.setText("R.U.T: ");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.EAST;
        gbc.insets = new Insets(10, 10, 10, 10);
        ventanaEmpleado.add(lblRut, gbc);
        lblTelefono = new JLabel();
        lblTelefono.setText("Teléfono: ");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.anchor = GridBagConstraints.EAST;
        gbc.insets = new Insets(10, 10, 10, 10);
        ventanaEmpleado.add(lblTelefono, gbc);
        lblRegion = new JLabel();
        lblRegion.setText("Región: ");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.anchor = GridBagConstraints.EAST;
        gbc.insets = new Insets(10, 10, 10, 10);
        ventanaEmpleado.add(lblRegion, gbc);
        lblCiudad = new JLabel();
        lblCiudad.setText("Ciudad: ");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 4;
        gbc.anchor = GridBagConstraints.EAST;
        gbc.insets = new Insets(10, 10, 10, 10);
        ventanaEmpleado.add(lblCiudad, gbc);
        lblCalle = new JLabel();
        lblCalle.setText("Calle: ");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 5;
        gbc.anchor = GridBagConstraints.EAST;
        gbc.insets = new Insets(10, 10, 10, 10);
        ventanaEmpleado.add(lblCalle, gbc);
        lblNumeroCasa = new JLabel();
        lblNumeroCasa.setText("Número de Casa: ");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 6;
        gbc.anchor = GridBagConstraints.EAST;
        gbc.insets = new Insets(10, 10, 10, 10);
        ventanaEmpleado.add(lblNumeroCasa, gbc);
        lblCargo = new JLabel();
        lblCargo.setText("Cargo: ");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 7;
        gbc.anchor = GridBagConstraints.EAST;
        gbc.insets = new Insets(10, 10, 10, 10);
        ventanaEmpleado.add(lblCargo, gbc);
        lblTurno = new JLabel();
        lblTurno.setText("Turno: ");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 8;
        gbc.anchor = GridBagConstraints.EAST;
        gbc.insets = new Insets(10, 10, 10, 10);
        ventanaEmpleado.add(lblTurno, gbc);
        lblSueldo = new JLabel();
        lblSueldo.setText("Sueldo: ");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 9;
        gbc.anchor = GridBagConstraints.EAST;
        gbc.insets = new Insets(10, 10, 10, 10);
        ventanaEmpleado.add(lblSueldo, gbc);
        txtNombre = new JTextField();
        txtNombre.setMaximumSize(new Dimension(350, 30));
        txtNombre.setMinimumSize(new Dimension(350, 30));
        txtNombre.setPreferredSize(new Dimension(350, 30));
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(10, 10, 10, 10);
        ventanaEmpleado.add(txtNombre, gbc);
        txtRut = new JTextField();
        txtRut.setMaximumSize(new Dimension(350, 30));
        txtRut.setMinimumSize(new Dimension(350, 30));
        txtRut.setPreferredSize(new Dimension(350, 30));
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(10, 10, 10, 10);
        ventanaEmpleado.add(txtRut, gbc);
        txtTelefono = new JTextField();
        txtTelefono.setMaximumSize(new Dimension(350, 30));
        txtTelefono.setMinimumSize(new Dimension(350, 30));
        txtTelefono.setPreferredSize(new Dimension(350, 30));
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 2;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(10, 10, 10, 10);
        ventanaEmpleado.add(txtTelefono, gbc);
        cmbRegion = new JComboBox();
        cmbRegion.setMaximumSize(new Dimension(350, 30));
        cmbRegion.setMinimumSize(new Dimension(350, 30));
        cmbRegion.setPreferredSize(new Dimension(350, 30));
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 3;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(10, 10, 10, 10);
        ventanaEmpleado.add(cmbRegion, gbc);
        cmbCiudad = new JComboBox();
        cmbCiudad.setMaximumSize(new Dimension(350, 30));
        cmbCiudad.setMinimumSize(new Dimension(350, 30));
        cmbCiudad.setPreferredSize(new Dimension(350, 30));
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 4;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(10, 10, 10, 10);
        ventanaEmpleado.add(cmbCiudad, gbc);
        txtCalle = new JTextField();
        txtCalle.setMaximumSize(new Dimension(350, 30));
        txtCalle.setMinimumSize(new Dimension(350, 30));
        txtCalle.setPreferredSize(new Dimension(350, 30));
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 5;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(10, 10, 10, 10);
        ventanaEmpleado.add(txtCalle, gbc);
        txtNumero = new JTextField();
        txtNumero.setMaximumSize(new Dimension(350, 30));
        txtNumero.setMinimumSize(new Dimension(350, 30));
        txtNumero.setPreferredSize(new Dimension(350, 30));
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 6;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(10, 10, 10, 10);
        ventanaEmpleado.add(txtNumero, gbc);
        txtCargo = new JTextField();
        txtCargo.setMaximumSize(new Dimension(350, 30));
        txtCargo.setMinimumSize(new Dimension(350, 30));
        txtCargo.setPreferredSize(new Dimension(350, 30));
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 7;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(10, 10, 10, 10);
        ventanaEmpleado.add(txtCargo, gbc);
        txtTurno = new JTextField();
        txtTurno.setMaximumSize(new Dimension(350, 30));
        txtTurno.setMinimumSize(new Dimension(350, 30));
        txtTurno.setPreferredSize(new Dimension(350, 30));
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 8;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(10, 10, 10, 10);
        ventanaEmpleado.add(txtTurno, gbc);
        txtSueldo = new JTextField();
        txtSueldo.setMaximumSize(new Dimension(350, 30));
        txtSueldo.setMinimumSize(new Dimension(350, 30));
        txtSueldo.setPreferredSize(new Dimension(350, 30));
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 9;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(10, 10, 10, 10);
        ventanaEmpleado.add(txtSueldo, gbc);
        contenedorBtns = new JPanel();
        contenedorBtns.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 10;
        gbc.gridwidth = 2;
        gbc.fill = GridBagConstraints.BOTH;
        ventanaEmpleado.add(contenedorBtns, gbc);
        btnRegistrarEmpleado = new JButton();
        btnRegistrarEmpleado.setText("Registrar Cliente");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(10, 10, 10, 10);
        contenedorBtns.add(btnRegistrarEmpleado, gbc);
        btnCancelarRegistro = new JButton();
        btnCancelarRegistro.setText("Cancelar Registro");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(10, 10, 10, 10);
        contenedorBtns.add(btnCancelarRegistro, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return ventanaEmpleado;
    }

}
