package com.llanquihuetour.ui;

import com.llanquihuetour.data.GestorReservas;
import com.llanquihuetour.util.CargadorCombobox;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;

/**
 * Clase que representa la interfaz gráfica de Gestión de Reservas.
 * Permite administrar las reservas de paquetes y servicios individuales.
 * @author Jaime Seguel.
 * @since Semana 9
 */
public class VentanaReservas extends JDialog {

    // Declaración de los elementos de la ventana.
    private JButton btnReservaServicio;
    private JButton btnReservaPaquete;
    private JLabel lblElegirFiltroReserva;
    private JComboBox cmbFiltroReserva;
    private JTextArea txtAreaReservas;
    private JButton btnVolver;
    private JLabel lblInstruccionesReservas;
    private JPanel contenedorBtns1;
    private JPanel ventanaReservas;

    /**
     * Constructor de la Ventana de Gestión de Reservas.
     * @param parent Ventana padre desde donde se invoca.
     */
    public VentanaReservas(JFrame parent) {

        super(parent, "Llanquihue Tour - Gestión de Reservas", true);
        this.setContentPane(ventanaReservas);
        this.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
        this.pack();
        this.setLocationRelativeTo(parent);

        // Evento del botón Volver.
        btnVolver.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {

                dispose();
            }
        });

        // Evento para abrir el registro de reserva de servicio.
        btnReservaServicio.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {

                VentanaReservaServicio ventana = new VentanaReservaServicio(VentanaReservas.this);
                ventana.setVisible(true);
            }
        });

        // Evento para abrir el registro de reserva de paquete.
        btnReservaPaquete.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {

                VentanaReservaPaquete ventana = new VentanaReservaPaquete(VentanaReservas.this);
                ventana.setVisible(true);
            }
        });

        // Llama al método que carga el combobox de filtros al iniciar la ventana.
        CargadorCombobox.cargarFiltrosEstadoReserva(cmbFiltroReserva);

        // Evento para actualizar el área de texto cuando cambia el filtro.
        cmbFiltroReserva.addItemListener(new java.awt.event.ItemListener() {

            public void itemStateChanged(java.awt.event.ItemEvent e) {

                if (e.getStateChange() == java.awt.event.ItemEvent.SELECTED) {

                    com.llanquihuetour.data.GestorReservas gestor = new com.llanquihuetour.data.GestorReservas();
                    txtAreaReservas.setText(gestor.obtenerResumenReservas(e.getItem().toString()));
                    txtAreaReservas.setCaretPosition(0);
                }
            }
        });

        // Carga inicial de datos en el área de texto
        com.llanquihuetour.data.GestorReservas gestorReservas = new com.llanquihuetour.data.GestorReservas();
        txtAreaReservas.setText(gestorReservas.obtenerResumenReservas("Todas"));
        txtAreaReservas.setCaretPosition(0);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        ventanaReservas = new JPanel();
        ventanaReservas.setLayout(new GridBagLayout());
        btnVolver = new JButton();
        btnVolver.setMaximumSize(new Dimension(200, 34));
        btnVolver.setMinimumSize(new Dimension(200, 34));
        btnVolver.setPreferredSize(new Dimension(200, 34));
        btnVolver.setText("Volver a la ventana principal");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 4;
        gbc.gridwidth = 2;
        gbc.insets = new Insets(10, 10, 10, 10);
        ventanaReservas.add(btnVolver, gbc);
        lblInstruccionesReservas = new JLabel();
        lblInstruccionesReservas.setText("Utilice esta ventana para registrar reservas de paquetes o servicios, y visualizar el registro actual.");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.gridwidth = 2;
        gbc.insets = new Insets(10, 10, 10, 10);
        ventanaReservas.add(lblInstruccionesReservas, gbc);
        final JScrollPane scrollPane1 = new JScrollPane();
        scrollPane1.setMaximumSize(new Dimension(600, 200));
        scrollPane1.setMinimumSize(new Dimension(600, 200));
        scrollPane1.setPreferredSize(new Dimension(600, 200));
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.gridwidth = 2;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.insets = new Insets(10, 10, 10, 10);
        ventanaReservas.add(scrollPane1, gbc);
        txtAreaReservas = new JTextArea();
        scrollPane1.setViewportView(txtAreaReservas);
        contenedorBtns1 = new JPanel();
        contenedorBtns1.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.gridwidth = 2;
        gbc.fill = GridBagConstraints.BOTH;
        ventanaReservas.add(contenedorBtns1, gbc);
        btnReservaServicio = new JButton();
        btnReservaServicio.setMaximumSize(new Dimension(198, 34));
        btnReservaServicio.setMinimumSize(new Dimension(198, 34));
        btnReservaServicio.setPreferredSize(new Dimension(198, 34));
        btnReservaServicio.setText("Reservar Servicio Turistico");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.insets = new Insets(10, 10, 10, 10);
        contenedorBtns1.add(btnReservaServicio, gbc);
        btnReservaPaquete = new JButton();
        btnReservaPaquete.setMaximumSize(new Dimension(198, 34));
        btnReservaPaquete.setMinimumSize(new Dimension(198, 34));
        btnReservaPaquete.setPreferredSize(new Dimension(198, 34));
        btnReservaPaquete.setText("Reservar Paquete Turistico");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.insets = new Insets(10, 10, 10, 10);
        contenedorBtns1.add(btnReservaPaquete, gbc);
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.gridwidth = 2;
        gbc.fill = GridBagConstraints.BOTH;
        ventanaReservas.add(panel1, gbc);
        lblElegirFiltroReserva = new JLabel();
        lblElegirFiltroReserva.setText("Elegir filtro");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.EAST;
        gbc.insets = new Insets(10, 10, 10, 10);
        panel1.add(lblElegirFiltroReserva, gbc);
        cmbFiltroReserva = new JComboBox();
        cmbFiltroReserva.setMaximumSize(new Dimension(350, 34));
        cmbFiltroReserva.setMinimumSize(new Dimension(350, 34));
        cmbFiltroReserva.setPreferredSize(new Dimension(350, 34));
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(10, 10, 10, 10);
        panel1.add(cmbFiltroReserva, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return ventanaReservas;
    }

}
