package com.llanquihuetour.ui;

import com.llanquihuetour.data.GestorCatalogo;
import com.llanquihuetour.model.ExcursionCultural;
import com.llanquihuetour.util.CargadorCombobox;
import com.llanquihuetour.util.ValidadorGeneral;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;

/**
 * Clase que representa la interfaz gráfica para registrar una Excursión Cultural.
 *
 * @author Jaime Seguel.
 * @since Semana 9
 */
public class VentanaExcursionCultural extends JDialog {

    // Declaración de los elementos de la ventana.
    private JPanel ventanaExcursion;
    private JButton btnRegistrarExcursion;
    private JTextField txtCodigo;
    private JTextField txtNombre;
    private JTextField txtDuracion;
    private JTextField txtComuna;
    private JTextField txtPrecio;
    private JTextField txtHorario;
    private JTextField txtLugarHistorico;
    private JTextField txtIdiomasGuia;
    private JComboBox cmbIncluyeEntradas;
    private JLabel lblCodigo;
    private JLabel lblNombre;
    private JLabel lblDuracion;
    private JLabel lblComuna;
    private JLabel lblPrecio;
    private JLabel lblHorario;
    private JLabel lblLugarHistorico;
    private JLabel lblIdiomas;
    private JLabel lblIncluyeEntradas;
    private JButton btnCancelarRegistro;
    private JPanel contenedorBtns;

    /**
     * Constructor de la Ventana Excursión Cultural.
     * @param parent Ventana padre desde donde se invoca.
     */
    public VentanaExcursionCultural(JDialog parent) {

        super(parent, "Registrar Excursión Cultural", true);
        this.setContentPane(ventanaExcursion);
        this.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
        this.pack();
        this.setLocationRelativeTo(parent);

        // Evento del botón Cancelar.
        btnCancelarRegistro.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                dispose();
            }
        });

        // Evento del botón Registrar
        btnRegistrarExcursion.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                registrarExcursion();
            }
        });

        // Llama al método que carga el combobox para los booleanos al iniciar la ventana.
        CargadorCombobox.cargarOpcionesSiNo(cmbIncluyeEntradas);
    }

    /**
     * Método que extrae, valida y guarda los datos de la excursión cultural en un .txt.
     */
    private void registrarExcursion() {

        String codigoStr = txtCodigo.getText();
        String nombre = txtNombre.getText();
        String duracionStr = txtDuracion.getText();
        String precioStr = txtPrecio.getText();
        String comuna = txtComuna.getText();
        String horario = txtHorario.getText();
        String lugar = txtLugarHistorico.getText();
        String idioma = txtIdiomasGuia.getText();
        boolean incluye = cmbIncluyeEntradas.getSelectedItem().toString().equals("Sí");

        if (ValidadorGeneral.validarCamposVacios(codigoStr, nombre, duracionStr, precioStr, comuna, horario, lugar, idioma)) {

            return;
        }

        int codigo = ValidadorGeneral.validarEntero(codigoStr, "Código");

        if (codigo == -1) {

            return;
        }

        double duracion = ValidadorGeneral.validarDecimal(duracionStr, "Duración");

        if (duracion == -1.0) {

            return;
        }

        double precio = ValidadorGeneral.validarDecimal(precioStr, "Precio");

        if (precio == -1.0) {

            return;
        }

        ExcursionCultural excursion = new ExcursionCultural(codigo, nombre, duracion, comuna, precio, horario, lugar, idioma, incluye);

        GestorCatalogo gestor = new GestorCatalogo();
        gestor.agregarProducto(excursion);

        JOptionPane.showMessageDialog(this, "Excursión Cultural registrada exitosamente.", "Registro Exitoso", JOptionPane.INFORMATION_MESSAGE);
        dispose();
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        ventanaExcursion = new JPanel();
        ventanaExcursion.setLayout(new GridBagLayout());
        lblCodigo = new JLabel();
        lblCodigo.setText("Código: ");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.EAST;
        gbc.insets = new Insets(10, 10, 10, 10);
        ventanaExcursion.add(lblCodigo, gbc);
        lblNombre = new JLabel();
        lblNombre.setText("Nombre: ");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.EAST;
        gbc.insets = new Insets(10, 10, 10, 10);
        ventanaExcursion.add(lblNombre, gbc);
        lblDuracion = new JLabel();
        lblDuracion.setText("Duración (Horas): ");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.anchor = GridBagConstraints.EAST;
        gbc.insets = new Insets(10, 10, 10, 10);
        ventanaExcursion.add(lblDuracion, gbc);
        lblComuna = new JLabel();
        lblComuna.setText("Comuna: ");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.anchor = GridBagConstraints.EAST;
        gbc.insets = new Insets(10, 10, 10, 10);
        ventanaExcursion.add(lblComuna, gbc);
        lblPrecio = new JLabel();
        lblPrecio.setText("Precio ($): ");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 4;
        gbc.anchor = GridBagConstraints.EAST;
        gbc.insets = new Insets(10, 10, 10, 10);
        ventanaExcursion.add(lblPrecio, gbc);
        lblHorario = new JLabel();
        lblHorario.setText("Horario: ");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 5;
        gbc.anchor = GridBagConstraints.EAST;
        gbc.insets = new Insets(10, 10, 10, 10);
        ventanaExcursion.add(lblHorario, gbc);
        lblLugarHistorico = new JLabel();
        lblLugarHistorico.setText("Lugar Histórico: ");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 6;
        gbc.anchor = GridBagConstraints.EAST;
        gbc.insets = new Insets(10, 10, 10, 10);
        ventanaExcursion.add(lblLugarHistorico, gbc);
        lblIdiomas = new JLabel();
        lblIdiomas.setText("Idiomas del Guía: ");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 7;
        gbc.anchor = GridBagConstraints.EAST;
        gbc.insets = new Insets(10, 10, 10, 10);
        ventanaExcursion.add(lblIdiomas, gbc);
        lblIncluyeEntradas = new JLabel();
        lblIncluyeEntradas.setText("¿Incluye Entradas?:");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 8;
        gbc.anchor = GridBagConstraints.EAST;
        gbc.insets = new Insets(10, 10, 10, 10);
        ventanaExcursion.add(lblIncluyeEntradas, gbc);
        txtCodigo = new JTextField();
        txtCodigo.setMaximumSize(new Dimension(350, 30));
        txtCodigo.setMinimumSize(new Dimension(350, 30));
        txtCodigo.setPreferredSize(new Dimension(350, 30));
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(10, 10, 10, 10);
        ventanaExcursion.add(txtCodigo, gbc);
        txtNombre = new JTextField();
        txtNombre.setMaximumSize(new Dimension(350, 30));
        txtNombre.setMinimumSize(new Dimension(350, 30));
        txtNombre.setPreferredSize(new Dimension(350, 30));
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(10, 10, 10, 10);
        ventanaExcursion.add(txtNombre, gbc);
        txtDuracion = new JTextField();
        txtDuracion.setMaximumSize(new Dimension(350, 30));
        txtDuracion.setMinimumSize(new Dimension(350, 30));
        txtDuracion.setPreferredSize(new Dimension(350, 30));
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 2;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(10, 10, 10, 10);
        ventanaExcursion.add(txtDuracion, gbc);
        txtComuna = new JTextField();
        txtComuna.setMaximumSize(new Dimension(350, 30));
        txtComuna.setMinimumSize(new Dimension(350, 30));
        txtComuna.setPreferredSize(new Dimension(350, 30));
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 3;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(10, 10, 10, 10);
        ventanaExcursion.add(txtComuna, gbc);
        txtPrecio = new JTextField();
        txtPrecio.setMaximumSize(new Dimension(350, 30));
        txtPrecio.setMinimumSize(new Dimension(350, 30));
        txtPrecio.setPreferredSize(new Dimension(350, 30));
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 4;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(10, 10, 10, 10);
        ventanaExcursion.add(txtPrecio, gbc);
        txtHorario = new JTextField();
        txtHorario.setMaximumSize(new Dimension(350, 30));
        txtHorario.setMinimumSize(new Dimension(350, 30));
        txtHorario.setPreferredSize(new Dimension(350, 30));
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 5;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(10, 10, 10, 10);
        ventanaExcursion.add(txtHorario, gbc);
        txtLugarHistorico = new JTextField();
        txtLugarHistorico.setMaximumSize(new Dimension(350, 30));
        txtLugarHistorico.setMinimumSize(new Dimension(350, 30));
        txtLugarHistorico.setPreferredSize(new Dimension(350, 30));
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 6;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(10, 10, 10, 10);
        ventanaExcursion.add(txtLugarHistorico, gbc);
        txtIdiomasGuia = new JTextField();
        txtIdiomasGuia.setMaximumSize(new Dimension(350, 30));
        txtIdiomasGuia.setMinimumSize(new Dimension(350, 30));
        txtIdiomasGuia.setPreferredSize(new Dimension(350, 30));
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 7;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(10, 10, 10, 10);
        ventanaExcursion.add(txtIdiomasGuia, gbc);
        cmbIncluyeEntradas = new JComboBox();
        cmbIncluyeEntradas.setMaximumSize(new Dimension(350, 30));
        cmbIncluyeEntradas.setMinimumSize(new Dimension(350, 30));
        cmbIncluyeEntradas.setPreferredSize(new Dimension(350, 30));
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 8;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(10, 10, 10, 10);
        ventanaExcursion.add(cmbIncluyeEntradas, gbc);
        contenedorBtns = new JPanel();
        contenedorBtns.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 9;
        gbc.gridwidth = 2;
        gbc.fill = GridBagConstraints.BOTH;
        ventanaExcursion.add(contenedorBtns, gbc);
        btnRegistrarExcursion = new JButton();
        btnRegistrarExcursion.setText("Registrar Excursión Cultural");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(10, 10, 10, 10);
        contenedorBtns.add(btnRegistrarExcursion, gbc);
        btnCancelarRegistro = new JButton();
        btnCancelarRegistro.setText("Cancelar Registro");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(10, 10, 10, 10);
        contenedorBtns.add(btnCancelarRegistro, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return ventanaExcursion;
    }

}
