package com.llanquihuetour.ui;

import com.llanquihuetour.data.GestorCatalogo;
import com.llanquihuetour.model.RutaGastronomica;
import com.llanquihuetour.util.CargadorCombobox;
import com.llanquihuetour.util.ValidadorGeneral;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;

/**
 * Clase que representa la interfaz gráfica para registrar una Ruta Gastronómica.
 * @author Jaime Seguel.
 * @since Semana 9
 */
public class VentanaRutaGastronomica extends JDialog {

    // Declaración de los elementos de la ventana.
    private JPanel ventanaRuta;
    private JButton btnRegistrarRuta;
    private JTextField txtCodigo;
    private JTextField txtNombre;
    private JTextField txtDuracion;
    private JTextField txtComuna;
    private JTextField txtPrecio;
    private JTextField txtHorario;
    private JTextField txtNumeroParadas;
    private JTextField txtCondicionAlimentaria;
    private JComboBox cmbOpcionVegetariana;
    private JButton btnCancelarRegistro;
    private JLabel lblCodigo;
    private JLabel lblNombre;
    private JLabel lblDuracion;
    private JLabel lblComuna;
    private JLabel lblPrecio;
    private JLabel lblHorario;
    private JLabel lblNumeroParadas;
    private JLabel lblOpcionVegetariana;
    private JLabel lblCondicionAlimentaria;
    private JPanel contenedorBtns;

    /**
     * Constructor de la Ventana Ruta Gastronómica.
     * @param parent Ventana padre desde donde se invoca.
     */
    public VentanaRutaGastronomica(JDialog parent) {

        super(parent, "Registrar Ruta Gastronómica", true);
        this.setContentPane(ventanaRuta);
        this.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
        this.pack();
        this.setLocationRelativeTo(parent);

        // Evento del botón Cancelar.
        btnCancelarRegistro.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {

                dispose();
            }
        });

        // Evento del botón Registrar.
        btnRegistrarRuta.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {

                registrarRuta();
            }
        });

        // Llama al método que carga el combobox del booleano al iniciar la ventana.
        CargadorCombobox.cargarOpcionesSiNo(cmbOpcionVegetariana);
    }

    /**
     * Método que extrae, valida y guarda los datos de la ruta gastronómica en el .txt.
     */
    private void registrarRuta() {

        String codigoStr = txtCodigo.getText();
        String nombre = txtNombre.getText();
        String duracionStr = txtDuracion.getText();
        String precioStr = txtPrecio.getText();
        String comuna = txtComuna.getText();
        String horario = txtHorario.getText();
        String paradasStr = txtNumeroParadas.getText();
        String condiciones = txtCondicionAlimentaria.getText();
        boolean vegetariana = cmbOpcionVegetariana.getSelectedItem().toString().equals("Sí");

        if (ValidadorGeneral.validarCamposVacios(codigoStr, nombre, duracionStr, precioStr, horario, paradasStr, condiciones)) {

            return;
        }

        int codigo = ValidadorGeneral.validarEntero(codigoStr, "Código");

        if (codigo == -1) {

            return;
        }

        double duracion = ValidadorGeneral.validarDecimal(duracionStr, "Duración");

        if (duracion == -1.0) {

            return;
        }

        double precio = ValidadorGeneral.validarDecimal(precioStr, "Precio");

        if (precio == -1.0) {

            return;
        }

        int paradas = ValidadorGeneral.validarEntero(paradasStr, "Número de Paradas");

        if (paradas == -1) {

            return;
        }

        RutaGastronomica ruta = new RutaGastronomica(codigo, nombre, duracion, comuna, precio, horario, paradas, vegetariana, condiciones);

        GestorCatalogo gestor = new GestorCatalogo();
        gestor.agregarProducto(ruta);

        JOptionPane.showMessageDialog(this, "Ruta Gastronómica registrada exitosamente.", "Registro Exitoso", JOptionPane.INFORMATION_MESSAGE);
        dispose();
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        ventanaRuta = new JPanel();
        ventanaRuta.setLayout(new GridBagLayout());
        lblCodigo = new JLabel();
        lblCodigo.setText("Código: ");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.EAST;
        gbc.insets = new Insets(10, 10, 10, 10);
        ventanaRuta.add(lblCodigo, gbc);
        lblNombre = new JLabel();
        lblNombre.setText("Nombre: ");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.EAST;
        gbc.insets = new Insets(10, 10, 10, 10);
        ventanaRuta.add(lblNombre, gbc);
        lblDuracion = new JLabel();
        lblDuracion.setText("Duración (Horas): ");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.anchor = GridBagConstraints.EAST;
        gbc.insets = new Insets(10, 10, 10, 10);
        ventanaRuta.add(lblDuracion, gbc);
        lblComuna = new JLabel();
        lblComuna.setText("Comuna: ");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.anchor = GridBagConstraints.EAST;
        gbc.insets = new Insets(10, 10, 10, 10);
        ventanaRuta.add(lblComuna, gbc);
        lblPrecio = new JLabel();
        lblPrecio.setText("Precio ($): ");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 4;
        gbc.anchor = GridBagConstraints.EAST;
        gbc.insets = new Insets(10, 10, 10, 10);
        ventanaRuta.add(lblPrecio, gbc);
        lblHorario = new JLabel();
        lblHorario.setText("Horario: ");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 5;
        gbc.anchor = GridBagConstraints.EAST;
        gbc.insets = new Insets(10, 10, 10, 10);
        ventanaRuta.add(lblHorario, gbc);
        lblNumeroParadas = new JLabel();
        lblNumeroParadas.setText("Número de Paradas: ");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 6;
        gbc.anchor = GridBagConstraints.EAST;
        gbc.insets = new Insets(10, 10, 10, 10);
        ventanaRuta.add(lblNumeroParadas, gbc);
        lblCondicionAlimentaria = new JLabel();
        lblCondicionAlimentaria.setText("Condición Alimentaria: ");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 7;
        gbc.anchor = GridBagConstraints.EAST;
        gbc.insets = new Insets(10, 10, 10, 10);
        ventanaRuta.add(lblCondicionAlimentaria, gbc);
        lblOpcionVegetariana = new JLabel();
        lblOpcionVegetariana.setText("¿Opción Vegetariana?: ");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 8;
        gbc.anchor = GridBagConstraints.EAST;
        gbc.insets = new Insets(10, 10, 10, 10);
        ventanaRuta.add(lblOpcionVegetariana, gbc);
        txtCodigo = new JTextField();
        txtCodigo.setMaximumSize(new Dimension(350, 30));
        txtCodigo.setMinimumSize(new Dimension(350, 30));
        txtCodigo.setPreferredSize(new Dimension(350, 30));
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(10, 10, 10, 10);
        ventanaRuta.add(txtCodigo, gbc);
        txtNombre = new JTextField();
        txtNombre.setMaximumSize(new Dimension(350, 30));
        txtNombre.setMinimumSize(new Dimension(350, 30));
        txtNombre.setPreferredSize(new Dimension(350, 30));
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(10, 10, 10, 10);
        ventanaRuta.add(txtNombre, gbc);
        txtDuracion = new JTextField();
        txtDuracion.setMaximumSize(new Dimension(350, 30));
        txtDuracion.setMinimumSize(new Dimension(350, 30));
        txtDuracion.setPreferredSize(new Dimension(350, 30));
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 2;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(10, 10, 10, 10);
        ventanaRuta.add(txtDuracion, gbc);
        txtComuna = new JTextField();
        txtComuna.setMaximumSize(new Dimension(350, 30));
        txtComuna.setMinimumSize(new Dimension(350, 30));
        txtComuna.setPreferredSize(new Dimension(350, 30));
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 3;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(10, 10, 10, 10);
        ventanaRuta.add(txtComuna, gbc);
        txtPrecio = new JTextField();
        txtPrecio.setMaximumSize(new Dimension(350, 30));
        txtPrecio.setMinimumSize(new Dimension(350, 30));
        txtPrecio.setPreferredSize(new Dimension(350, 30));
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 4;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(10, 10, 10, 10);
        ventanaRuta.add(txtPrecio, gbc);
        txtHorario = new JTextField();
        txtHorario.setMaximumSize(new Dimension(350, 30));
        txtHorario.setMinimumSize(new Dimension(350, 30));
        txtHorario.setPreferredSize(new Dimension(350, 30));
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 5;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(10, 10, 10, 10);
        ventanaRuta.add(txtHorario, gbc);
        txtNumeroParadas = new JTextField();
        txtNumeroParadas.setMaximumSize(new Dimension(350, 30));
        txtNumeroParadas.setMinimumSize(new Dimension(350, 30));
        txtNumeroParadas.setPreferredSize(new Dimension(350, 30));
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 6;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(10, 10, 10, 10);
        ventanaRuta.add(txtNumeroParadas, gbc);
        txtCondicionAlimentaria = new JTextField();
        txtCondicionAlimentaria.setMaximumSize(new Dimension(350, 30));
        txtCondicionAlimentaria.setMinimumSize(new Dimension(350, 30));
        txtCondicionAlimentaria.setPreferredSize(new Dimension(350, 30));
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 7;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(10, 10, 10, 10);
        ventanaRuta.add(txtCondicionAlimentaria, gbc);
        cmbOpcionVegetariana = new JComboBox();
        cmbOpcionVegetariana.setMaximumSize(new Dimension(350, 30));
        cmbOpcionVegetariana.setMinimumSize(new Dimension(350, 30));
        cmbOpcionVegetariana.setPreferredSize(new Dimension(350, 30));
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 8;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(10, 10, 10, 10);
        ventanaRuta.add(cmbOpcionVegetariana, gbc);
        contenedorBtns = new JPanel();
        contenedorBtns.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 9;
        gbc.gridwidth = 2;
        gbc.fill = GridBagConstraints.BOTH;
        ventanaRuta.add(contenedorBtns, gbc);
        btnRegistrarRuta = new JButton();
        btnRegistrarRuta.setText("Registrar Ruta Gastronómica");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(10, 10, 10, 10);
        contenedorBtns.add(btnRegistrarRuta, gbc);
        btnCancelarRegistro = new JButton();
        btnCancelarRegistro.setText("Cancelar Registro");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(10, 10, 10, 10);
        contenedorBtns.add(btnCancelarRegistro, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return ventanaRuta;
    }

}
