package com.llanquihuetour.ui;

import com.llanquihuetour.data.GestorPersonas;
import com.llanquihuetour.model.GuiaTuristico;
import com.llanquihuetour.model.Direccion;
import com.llanquihuetour.util.CargadorCombobox;
import com.llanquihuetour.util.RutInvalidoException;
import com.llanquihuetour.util.ValidadorGeneral;
import com.llanquihuetour.util.ValidadorRut;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;

/**
 * Clase que representa la interfaz gráfica para registrar un Guía Turístico.
 * @author Jaime Seguel.
 * @since Semana 9
 */
public class VentanaGuia extends JDialog {

    // Declaración de los elementos de la ventana.
    private JTextField txtNombre;
    private JTextField txtRut;
    private JTextField txtTelefono;
    private JComboBox cmbRegion;
    private JComboBox cmbCiudad;
    private JTextField txtCalle;
    private JTextField txtNumero;
    private JTextField txtIdiomas;
    private JTextField txtZonas;
    private JTextField txtCredencial;
    private JButton btnRegistrarGuia;
    private JButton btnCancelarRegistro;
    private JPanel ventanaGuia;
    private JLabel lblNombre;
    private JLabel lblRut;
    private JLabel lblTelefono;
    private JLabel lblRegion;
    private JLabel lblCiudad;
    private JLabel lblCalle;
    private JLabel lblNumeroCasa;
    private JLabel lblIdiomas;
    private JLabel lblZonaTrabajo;
    private JLabel lblCredencial;
    private JPanel contenedorBtns;

    /**
     * Constructor de la Ventana Guía Turístico.
     * @param parent Ventana padre desde donde se invoca.
     */
    public VentanaGuia(JDialog parent) {

        super(parent, "Registrar Guía Turístico", true);
        this.setContentPane(ventanaGuia);
        this.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
        this.pack();
        this.setLocationRelativeTo(parent);

        // Evento del botón Cancelar.
        btnCancelarRegistro.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                dispose();
            }
        });

        // Evento del botón Registrar.
        btnRegistrarGuia.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                registrarGuia();
            }
        });

        // Llama al método que carga los combobox de region y ciudad al iniciar la ventana.
        CargadorCombobox.cargarRegiones(cmbRegion);
        CargadorCombobox.actualizarCiudades(cmbRegion.getSelectedItem().toString(), cmbCiudad);

        // Actualización dinámica de ciudades al cambiar región
        cmbRegion.addItemListener(new ItemListener() {

            @Override
            public void itemStateChanged(ItemEvent e) {

                if (e.getStateChange() == ItemEvent.SELECTED) {
                    CargadorCombobox.actualizarCiudades(e.getItem().toString(), cmbCiudad);
                }
            }
        });
    }

    /**
     * Método que extrae, valida y guarda los datos del guía en un .txt.
     */
    private void registrarGuia() {

        String nombre = txtNombre.getText();
        String rut = txtRut.getText();
        String telefono = txtTelefono.getText();
        String region = cmbRegion.getSelectedItem().toString();
        String ciudad = cmbCiudad.getSelectedItem().toString();
        String calle = txtCalle.getText();
        String numero = txtNumero.getText();
        String idiomas = txtIdiomas.getText();
        String zona = txtZonas.getText();
        String credencial = txtCredencial.getText();

        if (ValidadorGeneral.validarCamposVacios(nombre, rut, telefono, calle, numero, idiomas, zona, credencial)) {
            return;
        }

        if (!ValidadorGeneral.validarTelefono(telefono)) {
            return;
        }

        if (ValidadorRut.validarRutGUI(rut) == null) {
            return;
        }

        Direccion direccion = new Direccion(calle, numero, ciudad, region);
        GuiaTuristico guia = new GuiaTuristico(nombre, rut, telefono, direccion, idiomas, zona, credencial);

        GestorPersonas gestor = new GestorPersonas();
        gestor.agregarPersona(guia);

        JOptionPane.showMessageDialog(this, "Guía Turístico registrado exitosamente.", "Registro Exitoso", JOptionPane.INFORMATION_MESSAGE);
        dispose();
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        ventanaGuia = new JPanel();
        ventanaGuia.setLayout(new GridBagLayout());
        lblNombre = new JLabel();
        lblNombre.setText("Nombre: ");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.EAST;
        gbc.insets = new Insets(10, 10, 10, 10);
        ventanaGuia.add(lblNombre, gbc);
        lblRut = new JLabel();
        lblRut.setText("R.U.T: ");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.EAST;
        gbc.insets = new Insets(10, 10, 10, 10);
        ventanaGuia.add(lblRut, gbc);
        lblTelefono = new JLabel();
        lblTelefono.setText("Teléfono: ");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.anchor = GridBagConstraints.EAST;
        gbc.insets = new Insets(10, 10, 10, 10);
        ventanaGuia.add(lblTelefono, gbc);
        lblRegion = new JLabel();
        lblRegion.setText("Región: ");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.anchor = GridBagConstraints.EAST;
        gbc.insets = new Insets(10, 10, 10, 10);
        ventanaGuia.add(lblRegion, gbc);
        lblCiudad = new JLabel();
        lblCiudad.setText("Ciudad: ");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 4;
        gbc.anchor = GridBagConstraints.EAST;
        gbc.insets = new Insets(10, 10, 10, 10);
        ventanaGuia.add(lblCiudad, gbc);
        lblCalle = new JLabel();
        lblCalle.setText("Calle: ");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 5;
        gbc.anchor = GridBagConstraints.EAST;
        gbc.insets = new Insets(10, 10, 10, 10);
        ventanaGuia.add(lblCalle, gbc);
        lblNumeroCasa = new JLabel();
        lblNumeroCasa.setText("Número de casa: ");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 6;
        gbc.anchor = GridBagConstraints.EAST;
        gbc.insets = new Insets(10, 10, 10, 10);
        ventanaGuia.add(lblNumeroCasa, gbc);
        lblIdiomas = new JLabel();
        lblIdiomas.setText("Idiomas: ");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 7;
        gbc.anchor = GridBagConstraints.EAST;
        gbc.insets = new Insets(10, 10, 10, 10);
        ventanaGuia.add(lblIdiomas, gbc);
        lblZonaTrabajo = new JLabel();
        lblZonaTrabajo.setText("Zonas de trabajo:");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 8;
        gbc.anchor = GridBagConstraints.EAST;
        gbc.insets = new Insets(10, 10, 10, 10);
        ventanaGuia.add(lblZonaTrabajo, gbc);
        lblCredencial = new JLabel();
        lblCredencial.setText("Credencial Sernatur: ");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 9;
        gbc.anchor = GridBagConstraints.EAST;
        gbc.insets = new Insets(10, 10, 10, 10);
        ventanaGuia.add(lblCredencial, gbc);
        txtNombre = new JTextField();
        txtNombre.setMaximumSize(new Dimension(350, 30));
        txtNombre.setMinimumSize(new Dimension(350, 30));
        txtNombre.setPreferredSize(new Dimension(350, 30));
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(10, 10, 10, 10);
        ventanaGuia.add(txtNombre, gbc);
        txtRut = new JTextField();
        txtRut.setMaximumSize(new Dimension(350, 30));
        txtRut.setMinimumSize(new Dimension(350, 30));
        txtRut.setPreferredSize(new Dimension(350, 30));
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(10, 10, 10, 10);
        ventanaGuia.add(txtRut, gbc);
        txtTelefono = new JTextField();
        txtTelefono.setMaximumSize(new Dimension(350, 30));
        txtTelefono.setMinimumSize(new Dimension(350, 30));
        txtTelefono.setPreferredSize(new Dimension(350, 30));
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 2;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(10, 10, 10, 10);
        ventanaGuia.add(txtTelefono, gbc);
        cmbRegion = new JComboBox();
        cmbRegion.setMaximumSize(new Dimension(350, 30));
        cmbRegion.setMinimumSize(new Dimension(350, 30));
        cmbRegion.setPreferredSize(new Dimension(350, 30));
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 3;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(10, 10, 10, 10);
        ventanaGuia.add(cmbRegion, gbc);
        cmbCiudad = new JComboBox();
        cmbCiudad.setMaximumSize(new Dimension(350, 30));
        cmbCiudad.setMinimumSize(new Dimension(350, 30));
        cmbCiudad.setPreferredSize(new Dimension(350, 30));
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 4;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(10, 10, 10, 10);
        ventanaGuia.add(cmbCiudad, gbc);
        txtCalle = new JTextField();
        txtCalle.setMaximumSize(new Dimension(350, 30));
        txtCalle.setMinimumSize(new Dimension(350, 30));
        txtCalle.setPreferredSize(new Dimension(350, 30));
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 5;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(10, 10, 10, 10);
        ventanaGuia.add(txtCalle, gbc);
        txtNumero = new JTextField();
        txtNumero.setMaximumSize(new Dimension(350, 30));
        txtNumero.setMinimumSize(new Dimension(350, 30));
        txtNumero.setPreferredSize(new Dimension(350, 30));
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 6;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(10, 10, 10, 10);
        ventanaGuia.add(txtNumero, gbc);
        txtIdiomas = new JTextField();
        txtIdiomas.setMaximumSize(new Dimension(350, 30));
        txtIdiomas.setMinimumSize(new Dimension(350, 30));
        txtIdiomas.setPreferredSize(new Dimension(350, 30));
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 7;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(10, 10, 10, 10);
        ventanaGuia.add(txtIdiomas, gbc);
        txtZonas = new JTextField();
        txtZonas.setMaximumSize(new Dimension(350, 30));
        txtZonas.setMinimumSize(new Dimension(350, 30));
        txtZonas.setPreferredSize(new Dimension(350, 30));
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 8;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(10, 10, 10, 10);
        ventanaGuia.add(txtZonas, gbc);
        txtCredencial = new JTextField();
        txtCredencial.setMaximumSize(new Dimension(350, 30));
        txtCredencial.setMinimumSize(new Dimension(350, 30));
        txtCredencial.setPreferredSize(new Dimension(350, 30));
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 9;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(10, 10, 10, 10);
        ventanaGuia.add(txtCredencial, gbc);
        contenedorBtns = new JPanel();
        contenedorBtns.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 10;
        gbc.gridwidth = 2;
        gbc.fill = GridBagConstraints.BOTH;
        ventanaGuia.add(contenedorBtns, gbc);
        btnRegistrarGuia = new JButton();
        btnRegistrarGuia.setText("Registrar Guia");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(10, 10, 10, 10);
        contenedorBtns.add(btnRegistrarGuia, gbc);
        btnCancelarRegistro = new JButton();
        btnCancelarRegistro.setText("Cancelar Registro");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(10, 10, 10, 10);
        contenedorBtns.add(btnCancelarRegistro, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return ventanaGuia;
    }

}
