package com.llanquihuetour.ui;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 * Clase que representa la interfaz gráfica principal (Bienvenida) de la aplicación.
 * @author Jaime Seguel.
 * @since Semana 9
 */
public class VentanaBienvenida extends JFrame {

    // Declaración de los elementos de la ventana.
    private JPanel ventanaBienvenida = new JPanel();
    private JLabel lblLogo = new JLabel();
    private JLabel lblDescripcion1 = new JLabel();
    private JLabel lblDescripcion2 = new JLabel();
    private JLabel lblDescripcion3 = new JLabel();
    private JLabel lblDescripcion4 = new JLabel();
    private JButton btnEmpresa = new JButton();
    private JButton btnReservas = new JButton();

    /**
     * Constructor de la ventana de bienvenida.
     */
    public VentanaBienvenida() {

        this.setContentPane(ventanaBienvenida);
        this.setTitle("Llanquihue Tour - Bienvenida");
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.pack();
        this.setLocationRelativeTo(null); // Centrar en pantalla
        lblLogo.setIcon(new ImageIcon(getClass().getResource("/images/Logo.png")));


        // Evento del botón que abre la Ventana de Gestión de Empresa.
        btnEmpresa.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {

                VentanaEmpresa ventana = new VentanaEmpresa(VentanaBienvenida.this);
                VentanaBienvenida.this.setVisible(false);
                ventana.setVisible(true);
                VentanaBienvenida.this.setVisible(true);
            }
        });

        // Evento del botón que abre la Ventana de Gestión de Reservas.
        btnReservas.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {

                VentanaReservas ventana = new VentanaReservas(VentanaBienvenida.this);
                VentanaBienvenida.this.setVisible(false);
                ventana.setVisible(true);
                VentanaBienvenida.this.setVisible(true);
            }
        });
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        ventanaBienvenida = new JPanel();
        ventanaBienvenida.setLayout(new GridBagLayout());
        ventanaBienvenida.setMaximumSize(new Dimension(600, 500));
        ventanaBienvenida.setMinimumSize(new Dimension(600, 500));
        ventanaBienvenida.setPreferredSize(new Dimension(600, 500));
        final JPanel spacer1 = new JPanel();
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 7;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        ventanaBienvenida.add(spacer1, gbc);
        final JPanel spacer2 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.gridheight = 4;
        gbc.fill = GridBagConstraints.VERTICAL;
        ventanaBienvenida.add(spacer2, gbc);
        lblLogo = new JLabel();
        lblLogo.setText("");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.gridwidth = 4;
        gbc.gridheight = 2;
        gbc.insets = new Insets(10, 10, 0, 10);
        ventanaBienvenida.add(lblLogo, gbc);
        lblDescripcion1 = new JLabel();
        lblDescripcion1.setText("Bienvenido al Sistema de Gestión de Llanquihue Tour.");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 3;
        gbc.gridwidth = 4;
        gbc.weightx = 1.0;
        gbc.insets = new Insets(10, 10, 2, 10);
        ventanaBienvenida.add(lblDescripcion1, gbc);
        lblDescripcion2 = new JLabel();
        lblDescripcion2.setText("Esta plataforma permite administrar el registro de clientes,");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 4;
        gbc.gridwidth = 4;
        gbc.weightx = 1.0;
        gbc.insets = new Insets(2, 10, 2, 10);
        ventanaBienvenida.add(lblDescripcion2, gbc);
        lblDescripcion3 = new JLabel();
        lblDescripcion3.setText("coordinar el personal y recursos internos, y gestionar");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 5;
        gbc.gridwidth = 4;
        gbc.weightx = 1.0;
        gbc.insets = new Insets(2, 10, 2, 10);
        ventanaBienvenida.add(lblDescripcion3, gbc);
        lblDescripcion4 = new JLabel();
        lblDescripcion4.setText("los servicios turísticos de la agencia.");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 6;
        gbc.gridwidth = 4;
        gbc.weightx = 1.0;
        gbc.insets = new Insets(2, 10, 15, 10);
        ventanaBienvenida.add(lblDescripcion4, gbc);
        btnEmpresa = new JButton();
        btnEmpresa.setMaximumSize(new Dimension(70, 34));
        btnEmpresa.setMinimumSize(new Dimension(70, 34));
        btnEmpresa.setPreferredSize(new Dimension(70, 34));
        btnEmpresa.setText("GESTIÓN DE EMPRESA");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 7;
        gbc.gridwidth = 2;
        gbc.weightx = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(10, 10, 10, 10);
        ventanaBienvenida.add(btnEmpresa, gbc);
        btnReservas = new JButton();
        btnReservas.setMaximumSize(new Dimension(70, 34));
        btnReservas.setMinimumSize(new Dimension(70, 34));
        btnReservas.setPreferredSize(new Dimension(70, 34));
        btnReservas.setText("GESTIÓN DE RESERVAS");
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 7;
        gbc.gridwidth = 2;
        gbc.weightx = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(10, 10, 10, 10);
        ventanaBienvenida.add(btnReservas, gbc);
        final JPanel spacer3 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 5;
        gbc.gridy = 7;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        ventanaBienvenida.add(spacer3, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return ventanaBienvenida;
    }

}
